### ISSUE TITLE
Switch from Google Sheet to Database 

### ISSUE THREAD

**Issue by luketd** [canadice/ssl-index#1]
- [x] Find and decide on database to use
- [x] Create workflow to the database for easy upload to the db
- [x] Create branch to switch from google sheets to database
- [x] Review and Merge

**Comment by canadice** [comment]
With the [Github Actions](https://github.com/canadice/shlrtools/tree/main/.github/workflows) that is now up and running for the SHL App, we can probably run the scraper and export that data to a database all within an R Script. That database could hopefully then be saved in the repository and then loaded in the Index all through R. SQLite should work for that with the code I started to use in the [SHL project](https://github.com/canadice/shl/tree/main/database).

**Comment by canadice** [comment]
A script `scraperJob.R` now exists that runs the daily scrape from the forum and writes a csv file (for the Google Sheet output) and overwrites the Daily_Scrape table in the SQLite database.

**Comment by canadice** [comment]
Review is completed. Merge is in process.
