### ISSUE TITLE
Primary keys

### ISSUE THREAD

**Issue by canadice** [canadice/ssl-index#2]
Primary keys for players should use their topic ID from their player page forum link.

Primary keys for game log data should be playerID, Season, Matchday combined.

Team information should use the teamID not franchiseID as those can be duplicated. 

Attributes and Availability needs a numeric ID as primary key. The values with spaces between them are not read properly on the Index afterwards.

**Comment by luketd** [comment]
Probably dont need primary keys for players or keeper data
